

default_platform(:ios)

platform :ios do
  desc "development version"
  lane :development do |options|
  	# tagName = options[:tag]
  	# git_pull(only_tags: true) 
  	# git_add(path: ".")
  	# git_commit(path: ".", message: "Version Bump")
  	# push_to_git_remote
  	# add_git_tag(tag: tagName)
  	# push_git_tags
    match(type: "development", force_for_new_devices: true) # 自动更新证书
    build_app(
		scheme: "jkFastlane",
		export_method: "development",
		output_directory: "/Users/yuangong/Desktop/jsFastlane",
		output_name: "development",
    clean: true,
		configuration: "Debug",
    export_xcargs: "-allowProvisioningUpdates",
    skip_profile_detection: true
	)
  end
end
